[package]
name = "intelbugminimal"
version = "0.1.0"
edition = "2018"

[dependencies]
rust-gpu-tools = { path = "/home/vmx/src/pl/filecoin/rust-gpu-tools", version = "0.5.0", default-features = false, features = ["opencl"] }
